### ISSUE TITLE
Limited Collaborator Role testing

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#143]
A new team member role is being introduced called "Limited Collaborator". This role is effectively the same as the Collaborator role but does not have access to pricing details.

The notable omission of pricing fields in response structures could potentially trigger errors in the TF provider.  We should fix any errors in using Terraform with this membership type and document a temporary lack of support for this membership type, if needed, and update field documentation to detail where the collaborator type will change the expected response.

Related to https://github.com/equinix/terraform-provider-metal/issues/142

**Comment by t0mk** [comment]
I run basic provider usage in projects and org where I had a LimitedCollaborator membership. It went OK.

I guess the problem here would be provider crashes on SIGSEGVs while trying to read data that were not populated in API responses because of the role constraints. I suggest we just proceed and fix problems that appear along the way. It should be just pointer reading sanitizing.

**Comment by displague** [comment]
Sounds good. We should be able to identify where these crashes are likely by first converting any pricing/billing properties in packngo to pointers (once we've identified that the response is optional/null, and not empty/zero).

**Comment by displague** [comment]
I've opened https://github.com/packethost/packngo/issues/299. We can revisit this issue after we have packngo support for the fields that need addressing.

If anyone runs into an issue using Limited Collaborator roles with the provider, comment on this issue or open a new one referring to this issue.
