### ISSUE TITLE
Update TF Acceptance tests to use TF 1.0.2

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#155]
I attempted to update the TF version in #154 to 1.0.2.  This resulting in the following error:

```
=== RUN   TestAccDataSourceMetalDevice_Basic
cannot run Terraform provider tests: unexpected error: openpgp: signature made by unknown entity
FAIL	github.com/equinix/terraform-provider-metal/metal	0.140s
```

**Comment by displague** [comment]
I suspect we will have this problem with 0.13.7, 0.12.31, etc.

**Comment by t0mk** [comment]
I tried acceptance tests with tf 1.0.2 and got `unsupported state format version: expected "0.1", got "0.2"`

.. which is caused by an old hashicorp json package: https://github.com/gruntwork-io/terratest/issues/943. We don't use the package directly in the provider but it's linked by tf-sdk. So to fix that, we need to

`go get github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0`

When I update the tf-plugin-sdk, it works with 

I will do a PR bumping the tf-sdk, and @displague can put there a github action test worker using TF 1.0.2. Maybe you can remove the 0.12, so we don't have too many of the tests running.

**Comment by displague** [comment]
It may be fair to only test with 1.0, and let users know that pre-1.0 Terrafrom users should use the 2.1.0 version.
Perhaps when a 1.1 or 2.0 comes out we can reconsider this.
